import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { RootState } from "../store";

export type Employee = {
    firstName?: string;
    lastName?: string;
    startDate?: string;
    department?: string;
    birthDate?: string;
    street?: string;
    city?: string;
    state?: string;
    zipCode?: string;
};

// Define a type for the slice state
interface EmployeeState {
    employees: Employee[];
}

// Define the initial state using that type
const initialState: EmployeeState = {
    employees: [
        {
            firstName: "John",
            lastName: "Doe",
            startDate: "2020-07-21",
            department: "Engineering",
            birthDate: "1990-01-15",
            street: "123 Main St",
            city: "New York",
            state: "NY",
            zipCode: "10001",
        },
        {
            firstName: "Jane",
            lastName: "Smith",
            startDate: "2021-05-10",
            department: "Marketing",
            birthDate: "1985-06-22",
            street: "456 Elm St",
            city: "Los Angeles",
            state: "CA",
            zipCode: "90001",
        },
        {
            firstName: "Michael",
            lastName: "Johnson",
            startDate: "2019-09-14",
            department: "Sales",
            birthDate: "1992-03-10",
            street: "789 Oak St",
            city: "Chicago",
            state: "IL",
            zipCode: "60601",
        },
        {
            firstName: "Emily",
            lastName: "Davis",
            startDate: "2018-11-30",
            department: "Human Resources",
            birthDate: "1988-07-05",
            street: "159 Pine St",
            city: "Houston",
            state: "TX",
            zipCode: "77001",
        },
        {
            firstName: "David",
            lastName: "Martinez",
            startDate: "2022-01-15",
            department: "Finance",
            birthDate: "1995-12-25",
            street: "753 Cedar St",
            city: "Phoenix",
            state: "AZ",
            zipCode: "85001",
        },
        {
            firstName: "Sarah",
            lastName: "Anderson",
            startDate: "2017-04-18",
            department: "Engineering",
            birthDate: "1987-09-12",
            street: "357 Birch St",
            city: "San Francisco",
            state: "CA",
            zipCode: "94101",
        },
        {
            firstName: "Robert",
            lastName: "Garcia",
            startDate: "2016-06-23",
            department: "Marketing",
            birthDate: "1983-11-30",
            street: "951 Maple St",
            city: "Denver",
            state: "CO",
            zipCode: "80201",
        },
        {
            firstName: "Jessica",
            lastName: "Wilson",
            startDate: "2023-02-10",
            department: "Sales",
            birthDate: "1998-05-08",
            street: "852 Cherry St",
            city: "Boston",
            state: "MA",
            zipCode: "02101",
        },
        {
            firstName: "Daniel",
            lastName: "Hernandez",
            startDate: "2015-08-04",
            department: "Human Resources",
            birthDate: "1982-06-17",
            street: "645 Spruce St",
            city: "Seattle",
            state: "WA",
            zipCode: "98101",
        },
        {
            firstName: "Ashley",
            lastName: "Moore",
            startDate: "2014-12-22",
            department: "Finance",
            birthDate: "1981-10-29",
            street: "369 Walnut St",
            city: "Atlanta",
            state: "GA",
            zipCode: "30301",
        },
        {
            firstName: "Brandon",
            lastName: "Clark",
            startDate: "2022-03-15",
            department: "Engineering",
            birthDate: "1997-08-19",
            street: "741 Aspen St",
            city: "Austin",
            state: "TX",
            zipCode: "73301",
        },
        {
            firstName: "Laura",
            lastName: "Rodriguez",
            startDate: "2013-09-09",
            department: "Marketing",
            birthDate: "1979-04-11",
            street: "258 Dogwood St",
            city: "Miami",
            state: "FL",
            zipCode: "33101",
        },
        {
            firstName: "Kevin",
            lastName: "Lewis",
            startDate: "2011-05-20",
            department: "Sales",
            birthDate: "1980-12-30",
            street: "963 Hickory St",
            city: "Portland",
            state: "OR",
            zipCode: "97201",
        },
        {
            firstName: "John",
            lastName: "Doe",
            startDate: "2020-07-21",
            department: "Engineering",
            birthDate: "1990-01-15",
            street: "123 Main St",
            city: "New York",
            state: "NY",
            zipCode: "10001",
        },
        {
            firstName: "Jane",
            lastName: "Smith",
            startDate: "2021-05-10",
            department: "Marketing",
            birthDate: "1985-06-22",
            street: "456 Elm St",
            city: "Los Angeles",
            state: "CA",
            zipCode: "90001",
        },
        {
            firstName: "Michael",
            lastName: "Johnson",
            startDate: "2019-09-14",
            department: "Sales",
            birthDate: "1992-03-10",
            street: "789 Oak St",
            city: "Chicago",
            state: "IL",
            zipCode: "60601",
        },
        {
            firstName: "Emily",
            lastName: "Davis",
            startDate: "2018-11-30",
            department: "Human Resources",
            birthDate: "1988-07-05",
            street: "159 Pine St",
            city: "Houston",
            state: "TX",
            zipCode: "77001",
        },
        {
            firstName: "David",
            lastName: "Martinez",
            startDate: "2022-01-15",
            department: "Finance",
            birthDate: "1995-12-25",
            street: "753 Cedar St",
            city: "Phoenix",
            state: "AZ",
            zipCode: "85001",
        },
        {
            firstName: "Sarah",
            lastName: "Anderson",
            startDate: "2017-04-18",
            department: "Engineering",
            birthDate: "1987-09-12",
            street: "357 Birch St",
            city: "San Francisco",
            state: "CA",
            zipCode: "94101",
        },
        {
            firstName: "Robert",
            lastName: "Garcia",
            startDate: "2016-06-23",
            department: "Marketing",
            birthDate: "1983-11-30",
            street: "951 Maple St",
            city: "Denver",
            state: "CO",
            zipCode: "80201",
        },
        {
            firstName: "Jessica",
            lastName: "Wilson",
            startDate: "2023-02-10",
            department: "Sales",
            birthDate: "1998-05-08",
            street: "852 Cherry St",
            city: "Boston",
            state: "MA",
            zipCode: "02101",
        },
        {
            firstName: "Daniel",
            lastName: "Hernandez",
            startDate: "2015-08-04",
            department: "Human Resources",
            birthDate: "1982-06-17",
            street: "645 Spruce St",
            city: "Seattle",
            state: "WA",
            zipCode: "98101",
        },
        {
            firstName: "Ashley",
            lastName: "Moore",
            startDate: "2014-12-22",
            department: "Finance",
            birthDate: "1981-10-29",
            street: "369 Walnut St",
            city: "Atlanta",
            state: "GA",
            zipCode: "30301",
        },
        {
            firstName: "Brandon",
            lastName: "Clark",
            startDate: "2022-03-15",
            department: "Engineering",
            birthDate: "1997-08-19",
            street: "741 Aspen St",
            city: "Austin",
            state: "TX",
            zipCode: "73301",
        },
        {
            firstName: "Laura",
            lastName: "Rodriguez",
            startDate: "2013-09-09",
            department: "Marketing",
            birthDate: "1979-04-11",
            street: "258 Dogwood St",
            city: "Miami",
            state: "FL",
            zipCode: "33101",
        },
        {
            firstName: "Kevin",
            lastName: "Lewis",
            startDate: "2011-05-20",
            department: "Sales",
            birthDate: "1980-12-30",
            street: "963 Hickory St",
            city: "Portland",
            state: "OR",
            zipCode: "97201",
        },
        {
            firstName: "John",
            lastName: "Doe",
            startDate: "2020-07-21",
            department: "Engineering",
            birthDate: "1990-01-15",
            street: "123 Main St",
            city: "New York",
            state: "NY",
            zipCode: "10001",
        },
        {
            firstName: "Jane",
            lastName: "Smith",
            startDate: "2021-05-10",
            department: "Marketing",
            birthDate: "1985-06-22",
            street: "456 Elm St",
            city: "Los Angeles",
            state: "CA",
            zipCode: "90001",
        },
        {
            firstName: "Michael",
            lastName: "Johnson",
            startDate: "2019-09-14",
            department: "Sales",
            birthDate: "1992-03-10",
            street: "789 Oak St",
            city: "Chicago",
            state: "IL",
            zipCode: "60601",
        },
        {
            firstName: "Emily",
            lastName: "Davis",
            startDate: "2018-11-30",
            department: "Human Resources",
            birthDate: "1988-07-05",
            street: "159 Pine St",
            city: "Houston",
            state: "TX",
            zipCode: "77001",
        },
        {
            firstName: "David",
            lastName: "Martinez",
            startDate: "2022-01-15",
            department: "Finance",
            birthDate: "1995-12-25",
            street: "753 Cedar St",
            city: "Phoenix",
            state: "AZ",
            zipCode: "85001",
        },
        {
            firstName: "Sarah",
            lastName: "Anderson",
            startDate: "2017-04-18",
            department: "Engineering",
            birthDate: "1987-09-12",
            street: "357 Birch St",
            city: "San Francisco",
            state: "CA",
            zipCode: "94101",
        },
        {
            firstName: "Robert",
            lastName: "Garcia",
            startDate: "2016-06-23",
            department: "Marketing",
            birthDate: "1983-11-30",
            street: "951 Maple St",
            city: "Denver",
            state: "CO",
            zipCode: "80201",
        },
        {
            firstName: "Jessica",
            lastName: "Wilson",
            startDate: "2023-02-10",
            department: "Sales",
            birthDate: "1998-05-08",
            street: "852 Cherry St",
            city: "Boston",
            state: "MA",
            zipCode: "02101",
        },
        {
            firstName: "Daniel",
            lastName: "Hernandez",
            startDate: "2015-08-04",
            department: "Human Resources",
            birthDate: "1982-06-17",
            street: "645 Spruce St",
            city: "Seattle",
            state: "WA",
            zipCode: "98101",
        },
        {
            firstName: "Ashley",
            lastName: "Moore",
            startDate: "2014-12-22",
            department: "Finance",
            birthDate: "1981-10-29",
            street: "369 Walnut St",
            city: "Atlanta",
            state: "GA",
            zipCode: "30301",
        },
        {
            firstName: "Brandon",
            lastName: "Clark",
            startDate: "2022-03-15",
            department: "Engineering",
            birthDate: "1997-08-19",
            street: "741 Aspen St",
            city: "Austin",
            state: "TX",
            zipCode: "73301",
        },
        {
            firstName: "Laura",
            lastName: "Rodriguez",
            startDate: "2013-09-09",
            department: "Marketing",
            birthDate: "1979-04-11",
            street: "258 Dogwood St",
            city: "Miami",
            state: "FL",
            zipCode: "33101",
        },
        {
            firstName: "Kevin",
            lastName: "Lewis",
            startDate: "2011-05-20",
            department: "Sales",
            birthDate: "1980-12-30",
            street: "963 Hickory St",
            city: "Portland",
            state: "OR",
            zipCode: "97201",
        },
        {
            firstName: "John",
            lastName: "Doe",
            startDate: "2020-07-21",
            department: "Engineering",
            birthDate: "1990-01-15",
            street: "123 Main St",
            city: "New York",
            state: "NY",
            zipCode: "10001",
        },
        {
            firstName: "Jane",
            lastName: "Smith",
            startDate: "2021-05-10",
            department: "Marketing",
            birthDate: "1985-06-22",
            street: "456 Elm St",
            city: "Los Angeles",
            state: "CA",
            zipCode: "90001",
        },
        {
            firstName: "Michael",
            lastName: "Johnson",
            startDate: "2019-09-14",
            department: "Sales",
            birthDate: "1992-03-10",
            street: "789 Oak St",
            city: "Chicago",
            state: "IL",
            zipCode: "60601",
        },
        {
            firstName: "Emily",
            lastName: "Davis",
            startDate: "2018-11-30",
            department: "Human Resources",
            birthDate: "1988-07-05",
            street: "159 Pine St",
            city: "Houston",
            state: "TX",
            zipCode: "77001",
        },
        {
            firstName: "David",
            lastName: "Martinez",
            startDate: "2022-01-15",
            department: "Finance",
            birthDate: "1995-12-25",
            street: "753 Cedar St",
            city: "Phoenix",
            state: "AZ",
            zipCode: "85001",
        },
        {
            firstName: "Sarah",
            lastName: "Anderson",
            startDate: "2017-04-18",
            department: "Engineering",
            birthDate: "1987-09-12",
            street: "357 Birch St",
            city: "San Francisco",
            state: "CA",
            zipCode: "94101",
        },
        {
            firstName: "Robert",
            lastName: "Garcia",
            startDate: "2016-06-23",
            department: "Marketing",
            birthDate: "1983-11-30",
            street: "951 Maple St",
            city: "Denver",
            state: "CO",
            zipCode: "80201",
        },
        {
            firstName: "Jessica",
            lastName: "Wilson",
            startDate: "2023-02-10",
            department: "Sales",
            birthDate: "1998-05-08",
            street: "852 Cherry St",
            city: "Boston",
            state: "MA",
            zipCode: "02101",
        },
        {
            firstName: "Daniel",
            lastName: "Hernandez",
            startDate: "2015-08-04",
            department: "Human Resources",
            birthDate: "1982-06-17",
            street: "645 Spruce St",
            city: "Seattle",
            state: "WA",
            zipCode: "98101",
        },
        {
            firstName: "Ashley",
            lastName: "Moore",
            startDate: "2014-12-22",
            department: "Finance",
            birthDate: "1981-10-29",
            street: "369 Walnut St",
            city: "Atlanta",
            state: "GA",
            zipCode: "30301",
        },
        {
            firstName: "Brandon",
            lastName: "Clark",
            startDate: "2022-03-15",
            department: "Engineering",
            birthDate: "1997-08-19",
            street: "741 Aspen St",
            city: "Austin",
            state: "TX",
            zipCode: "73301",
        },
        {
            firstName: "Laura",
            lastName: "Rodriguez",
            startDate: "2013-09-09",
            department: "Marketing",
            birthDate: "1979-04-11",
            street: "258 Dogwood St",
            city: "Miami",
            state: "FL",
            zipCode: "33101",
        },
        {
            firstName: "Kevin",
            lastName: "Lewis",
            startDate: "2011-05-20",
            department: "Sales",
            birthDate: "1980-12-30",
            street: "963 Hickory St",
            city: "Portland",
            state: "OR",
            zipCode: "97201",
        },
        {
            firstName: "John",
            lastName: "Doe",
            startDate: "2020-07-21",
            department: "Engineering",
            birthDate: "1990-01-15",
            street: "123 Main St",
            city: "New York",
            state: "NY",
            zipCode: "10001",
        },
        {
            firstName: "Jane",
            lastName: "Smith",
            startDate: "2021-05-10",
            department: "Marketing",
            birthDate: "1985-06-22",
            street: "456 Elm St",
            city: "Los Angeles",
            state: "CA",
            zipCode: "90001",
        },
        {
            firstName: "Michael",
            lastName: "Johnson",
            startDate: "2019-09-14",
            department: "Sales",
            birthDate: "1992-03-10",
            street: "789 Oak St",
            city: "Chicago",
            state: "IL",
            zipCode: "60601",
        },
        {
            firstName: "Emily",
            lastName: "Davis",
            startDate: "2018-11-30",
            department: "Human Resources",
            birthDate: "1988-07-05",
            street: "159 Pine St",
            city: "Houston",
            state: "TX",
            zipCode: "77001",
        },
        {
            firstName: "David",
            lastName: "Martinez",
            startDate: "2022-01-15",
            department: "Finance",
            birthDate: "1995-12-25",
            street: "753 Cedar St",
            city: "Phoenix",
            state: "AZ",
            zipCode: "85001",
        },
        {
            firstName: "Sarah",
            lastName: "Anderson",
            startDate: "2017-04-18",
            department: "Engineering",
            birthDate: "1987-09-12",
            street: "357 Birch St",
            city: "San Francisco",
            state: "CA",
            zipCode: "94101",
        },
        {
            firstName: "Robert",
            lastName: "Garcia",
            startDate: "2016-06-23",
            department: "Marketing",
            birthDate: "1983-11-30",
            street: "951 Maple St",
            city: "Denver",
            state: "CO",
            zipCode: "80201",
        },
        {
            firstName: "Jessica",
            lastName: "Wilson",
            startDate: "2023-02-10",
            department: "Sales",
            birthDate: "1998-05-08",
            street: "852 Cherry St",
            city: "Boston",
            state: "MA",
            zipCode: "02101",
        },
        {
            firstName: "Daniel",
            lastName: "Hernandez",
            startDate: "2015-08-04",
            department: "Human Resources",
            birthDate: "1982-06-17",
            street: "645 Spruce St",
            city: "Seattle",
            state: "WA",
            zipCode: "98101",
        },
        {
            firstName: "Ashley",
            lastName: "Moore",
            startDate: "2014-12-22",
            department: "Finance",
            birthDate: "1981-10-29",
            street: "369 Walnut St",
            city: "Atlanta",
            state: "GA",
            zipCode: "30301",
        },
        {
            firstName: "Brandon",
            lastName: "Clark",
            startDate: "2022-03-15",
            department: "Engineering",
            birthDate: "1997-08-19",
            street: "741 Aspen St",
            city: "Austin",
            state: "TX",
            zipCode: "73301",
        },
        {
            firstName: "Laura",
            lastName: "Rodriguez",
            startDate: "2013-09-09",
            department: "Marketing",
            birthDate: "1979-04-11",
            street: "258 Dogwood St",
            city: "Miami",
            state: "FL",
            zipCode: "33101",
        },
        {
            firstName: "Kevin",
            lastName: "Lewis",
            startDate: "2011-05-20",
            department: "Sales",
            birthDate: "1980-12-30",
            street: "963 Hickory St",
            city: "Portland",
            state: "OR",
            zipCode: "97201",
        },
        {
            firstName: "John",
            lastName: "Doe",
            startDate: "2020-07-21",
            department: "Engineering",
            birthDate: "1990-01-15",
            street: "123 Main St",
            city: "New York",
            state: "NY",
            zipCode: "10001",
        },
        {
            firstName: "Jane",
            lastName: "Smith",
            startDate: "2021-05-10",
            department: "Marketing",
            birthDate: "1985-06-22",
            street: "456 Elm St",
            city: "Los Angeles",
            state: "CA",
            zipCode: "90001",
        },
        {
            firstName: "Michael",
            lastName: "Johnson",
            startDate: "2019-09-14",
            department: "Sales",
            birthDate: "1992-03-10",
            street: "789 Oak St",
            city: "Chicago",
            state: "IL",
            zipCode: "60601",
        },
        {
            firstName: "Emily",
            lastName: "Davis",
            startDate: "2018-11-30",
            department: "Human Resources",
            birthDate: "1988-07-05",
            street: "159 Pine St",
            city: "Houston",
            state: "TX",
            zipCode: "77001",
        },
        {
            firstName: "David",
            lastName: "Martinez",
            startDate: "2022-01-15",
            department: "Finance",
            birthDate: "1995-12-25",
            street: "753 Cedar St",
            city: "Phoenix",
            state: "AZ",
            zipCode: "85001",
        },
        {
            firstName: "Sarah",
            lastName: "Anderson",
            startDate: "2017-04-18",
            department: "Engineering",
            birthDate: "1987-09-12",
            street: "357 Birch St",
            city: "San Francisco",
            state: "CA",
            zipCode: "94101",
        },
        {
            firstName: "Robert",
            lastName: "Garcia",
            startDate: "2016-06-23",
            department: "Marketing",
            birthDate: "1983-11-30",
            street: "951 Maple St",
            city: "Denver",
            state: "CO",
            zipCode: "80201",
        },
        {
            firstName: "Jessica",
            lastName: "Wilson",
            startDate: "2023-02-10",
            department: "Sales",
            birthDate: "1998-05-08",
            street: "852 Cherry St",
            city: "Boston",
            state: "MA",
            zipCode: "02101",
        },
        {
            firstName: "Daniel",
            lastName: "Hernandez",
            startDate: "2015-08-04",
            department: "Human Resources",
            birthDate: "1982-06-17",
            street: "645 Spruce St",
            city: "Seattle",
            state: "WA",
            zipCode: "98101",
        },
        {
            firstName: "Ashley",
            lastName: "Moore",
            startDate: "2014-12-22",
            department: "Finance",
            birthDate: "1981-10-29",
            street: "369 Walnut St",
            city: "Atlanta",
            state: "GA",
            zipCode: "30301",
        },
        {
            firstName: "Brandon",
            lastName: "Clark",
            startDate: "2022-03-15",
            department: "Engineering",
            birthDate: "1997-08-19",
            street: "741 Aspen St",
            city: "Austin",
            state: "TX",
            zipCode: "73301",
        },
        {
            firstName: "Laura",
            lastName: "Rodriguez",
            startDate: "2013-09-09",
            department: "Marketing",
            birthDate: "1979-04-11",
            street: "258 Dogwood St",
            city: "Miami",
            state: "FL",
            zipCode: "33101",
        },
        {
            firstName: "Kevin",
            lastName: "Lewis",
            startDate: "2011-05-20",
            department: "Sales",
            birthDate: "1980-12-30",
            street: "963 Hickory St",
            city: "Portland",
            state: "OR",
            zipCode: "97201",
        },
        {
            firstName: "John",
            lastName: "Doe",
            startDate: "2020-07-21",
            department: "Engineering",
            birthDate: "1990-01-15",
            street: "123 Main St",
            city: "New York",
            state: "NY",
            zipCode: "10001",
        },
        {
            firstName: "Jane",
            lastName: "Smith",
            startDate: "2021-05-10",
            department: "Marketing",
            birthDate: "1985-06-22",
            street: "456 Elm St",
            city: "Los Angeles",
            state: "CA",
            zipCode: "90001",
        },
        {
            firstName: "Michael",
            lastName: "Johnson",
            startDate: "2019-09-14",
            department: "Sales",
            birthDate: "1992-03-10",
            street: "789 Oak St",
            city: "Chicago",
            state: "IL",
            zipCode: "60601",
        },
        {
            firstName: "Emily",
            lastName: "Davis",
            startDate: "2018-11-30",
            department: "Human Resources",
            birthDate: "1988-07-05",
            street: "159 Pine St",
            city: "Houston",
            state: "TX",
            zipCode: "77001",
        },
        {
            firstName: "David",
            lastName: "Martinez",
            startDate: "2022-01-15",
            department: "Finance",
            birthDate: "1995-12-25",
            street: "753 Cedar St",
            city: "Phoenix",
            state: "AZ",
            zipCode: "85001",
        },
        {
            firstName: "Sarah",
            lastName: "Anderson",
            startDate: "2017-04-18",
            department: "Engineering",
            birthDate: "1987-09-12",
            street: "357 Birch St",
            city: "San Francisco",
            state: "CA",
            zipCode: "94101",
        },
        {
            firstName: "Robert",
            lastName: "Garcia",
            startDate: "2016-06-23",
            department: "Marketing",
            birthDate: "1983-11-30",
            street: "951 Maple St",
            city: "Denver",
            state: "CO",
            zipCode: "80201",
        },
        {
            firstName: "Jessica",
            lastName: "Wilson",
            startDate: "2023-02-10",
            department: "Sales",
            birthDate: "1998-05-08",
            street: "852 Cherry St",
            city: "Boston",
            state: "MA",
            zipCode: "02101",
        },
        {
            firstName: "Daniel",
            lastName: "Hernandez",
            startDate: "2015-08-04",
            department: "Human Resources",
            birthDate: "1982-06-17",
            street: "645 Spruce St",
            city: "Seattle",
            state: "WA",
            zipCode: "98101",
        },
        {
            firstName: "Ashley",
            lastName: "Moore",
            startDate: "2014-12-22",
            department: "Finance",
            birthDate: "1981-10-29",
            street: "369 Walnut St",
            city: "Atlanta",
            state: "GA",
            zipCode: "30301",
        },
        {
            firstName: "Brandon",
            lastName: "Clark",
            startDate: "2022-03-15",
            department: "Engineering",
            birthDate: "1997-08-19",
            street: "741 Aspen St",
            city: "Austin",
            state: "TX",
            zipCode: "73301",
        },
        {
            firstName: "Laura",
            lastName: "Rodriguez",
            startDate: "2013-09-09",
            department: "Marketing",
            birthDate: "1979-04-11",
            street: "258 Dogwood St",
            city: "Miami",
            state: "FL",
            zipCode: "33101",
        },
        {
            firstName: "Kevin",
            lastName: "Lewis",
            startDate: "2011-05-20",
            department: "Sales",
            birthDate: "1980-12-30",
            street: "963 Hickory St",
            city: "Portland",
            state: "OR",
            zipCode: "97201",
        },
        {
            firstName: "Sarah",
            lastName: "Anderson",
            startDate: "2017-04-18",
            department: "Engineering",
            birthDate: "1987-09-12",
            street: "357 Birch St",
            city: "San Francisco",
            state: "CA",
            zipCode: "94101",
        },
        {
            firstName: "Robert",
            lastName: "Garcia",
            startDate: "2016-06-23",
            department: "Marketing",
            birthDate: "1983-11-30",
            street: "951 Maple St",
            city: "Denver",
            state: "CO",
            zipCode: "80201",
        },
        {
            firstName: "Jessica",
            lastName: "Wilson",
            startDate: "2023-02-10",
            department: "Sales",
            birthDate: "1998-05-08",
            street: "852 Cherry St",
            city: "Boston",
            state: "MA",
            zipCode: "02101",
        },
        {
            firstName: "Daniel",
            lastName: "Hernandez",
            startDate: "2015-08-04",
            department: "Human Resources",
            birthDate: "1982-06-17",
            street: "645 Spruce St",
            city: "Seattle",
            state: "WA",
            zipCode: "98101",
        },
        {
            firstName: "Ashley",
            lastName: "Moore",
            startDate: "2014-12-22",
            department: "Finance",
            birthDate: "1981-10-29",
            street: "369 Walnut St",
            city: "Atlanta",
            state: "GA",
            zipCode: "30301",
        },
        {
            firstName: "Brandon",
            lastName: "Clark",
            startDate: "2022-03-15",
            department: "Engineering",
            birthDate: "1997-08-19",
            street: "741 Aspen St",
            city: "Austin",
            state: "TX",
            zipCode: "73301",
        },
        {
            firstName: "Laura",
            lastName: "Rodriguez",
            startDate: "2013-09-09",
            department: "Marketing",
            birthDate: "1979-04-11",
            street: "258 Dogwood St",
            city: "Miami",
            state: "FL",
            zipCode: "33101",
        },
        {
            firstName: "Kevin",
            lastName: "Lewis",
            startDate: "2011-05-20",
            department: "Sales",
            birthDate: "1980-12-30",
            street: "963 Hickory St",
            city: "Portland",
            state: "OR",
            zipCode: "97201",
        },
        {
            firstName: "John",
            lastName: "Doe",
            startDate: "2020-07-21",
            department: "Engineering",
            birthDate: "1990-01-15",
            street: "123 Main St",
            city: "New York",
            state: "NY",
            zipCode: "10001",
        },
        {
            firstName: "Jane",
            lastName: "Smith",
            startDate: "2021-05-10",
            department: "Marketing",
            birthDate: "1985-06-22",
            street: "456 Elm St",
            city: "Los Angeles",
            state: "CA",
            zipCode: "90001",
        },
        {
            firstName: "Michael",
            lastName: "Johnson",
            startDate: "2019-09-14",
            department: "Sales",
            birthDate: "1992-03-10",
            street: "789 Oak St",
            city: "Chicago",
            state: "IL",
            zipCode: "60601",
        },
        {
            firstName: "Emily",
            lastName: "Davis",
            startDate: "2018-11-30",
            department: "Human Resources",
            birthDate: "1988-07-05",
            street: "159 Pine St",
            city: "Houston",
            state: "TX",
            zipCode: "77001",
        },
        {
            firstName: "David",
            lastName: "Martinez",
            startDate: "2022-01-15",
            department: "Finance",
            birthDate: "1995-12-25",
            street: "753 Cedar St",
            city: "Phoenix",
            state: "AZ",
            zipCode: "85001",
        },
        {
            firstName: "Sarah",
            lastName: "Anderson",
            startDate: "2017-04-18",
            department: "Engineering",
            birthDate: "1987-09-12",
            street: "357 Birch St",
            city: "San Francisco",
            state: "CA",
            zipCode: "94101",
        },
        {
            firstName: "Robert",
            lastName: "Garcia",
            startDate: "2016-06-23",
            department: "Marketing",
            birthDate: "1983-11-30",
            street: "951 Maple St",
            city: "Denver",
            state: "CO",
            zipCode: "80201",
        },
        {
            firstName: "Jessica",
            lastName: "Wilson",
            startDate: "2023-02-10",
            department: "Sales",
            birthDate: "1998-05-08",
            street: "852 Cherry St",
            city: "Boston",
            state: "MA",
            zipCode: "02101",
        },
        {
            firstName: "Daniel",
            lastName: "Hernandez",
            startDate: "2015-08-04",
            department: "Human Resources",
            birthDate: "1982-06-17",
            street: "645 Spruce St",
            city: "Seattle",
            state: "WA",
            zipCode: "98101",
        },
        {
            firstName: "Ashley",
            lastName: "Moore",
            startDate: "2014-12-22",
            department: "Finance",
            birthDate: "1981-10-29",
            street: "369 Walnut St",
            city: "Atlanta",
            state: "GA",
            zipCode: "30301",
        },
        {
            firstName: "Brandon",
            lastName: "Clark",
            startDate: "2022-03-15",
            department: "Engineering",
            birthDate: "1997-08-19",
            street: "741 Aspen St",
            city: "Austin",
            state: "TX",
            zipCode: "73301",
        },
        {
            firstName: "Laura",
            lastName: "Rodriguez",
            startDate: "2013-09-09",
            department: "Marketing",
            birthDate: "1979-04-11",
            street: "258 Dogwood St",
            city: "Miami",
            state: "FL",
            zipCode: "33101",
        },
        {
            firstName: "Kevin",
            lastName: "Lewis",
            startDate: "2011-05-20",
            department: "Sales",
            birthDate: "1980-12-30",
            street: "963 Hickory St",
            city: "Portland",
            state: "OR",
            zipCode: "97201",
        },
        {
            firstName: "John",
            lastName: "Doe",
            startDate: "2020-07-21",
            department: "Engineering",
            birthDate: "1990-01-15",
            street: "123 Main St",
            city: "New York",
            state: "NY",
            zipCode: "10001",
        },
        {
            firstName: "Jane",
            lastName: "Smith",
            startDate: "2021-05-10",
            department: "Marketing",
            birthDate: "1985-06-22",
            street: "456 Elm St",
            city: "Los Angeles",
            state: "CA",
            zipCode: "90001",
        },
        {
            firstName: "Michael",
            lastName: "Johnson",
            startDate: "2019-09-14",
            department: "Sales",
            birthDate: "1992-03-10",
            street: "789 Oak St",
            city: "Chicago",
            state: "IL",
            zipCode: "60601",
        },
        {
            firstName: "Emily",
            lastName: "Davis",
            startDate: "2018-11-30",
            department: "Human Resources",
            birthDate: "1988-07-05",
            street: "159 Pine St",
            city: "Houston",
            state: "TX",
            zipCode: "77001",
        },
        {
            firstName: "David",
            lastName: "Martinez",
            startDate: "2022-01-15",
            department: "Finance",
            birthDate: "1995-12-25",
            street: "753 Cedar St",
            city: "Phoenix",
            state: "AZ",
            zipCode: "85001",
        },
        {
            firstName: "Sarah",
            lastName: "Anderson",
            startDate: "2017-04-18",
            department: "Engineering",
            birthDate: "1987-09-12",
            street: "357 Birch St",
            city: "San Francisco",
            state: "CA",
            zipCode: "94101",
        },
        {
            firstName: "Robert",
            lastName: "Garcia",
            startDate: "2016-06-23",
            department: "Marketing",
            birthDate: "1983-11-30",
            street: "951 Maple St",
            city: "Denver",
            state: "CO",
            zipCode: "80201",
        },
        {
            firstName: "Jessica",
            lastName: "Wilson",
            startDate: "2023-02-10",
            department: "Sales",
            birthDate: "1998-05-08",
            street: "852 Cherry St",
            city: "Boston",
            state: "MA",
            zipCode: "02101",
        },
        {
            firstName: "Daniel",
            lastName: "Hernandez",
            startDate: "2015-08-04",
            department: "Human Resources",
            birthDate: "1982-06-17",
            street: "645 Spruce St",
            city: "Seattle",
            state: "WA",
            zipCode: "98101",
        },
        {
            firstName: "Ashley",
            lastName: "Moore",
            startDate: "2014-12-22",
            department: "Finance",
            birthDate: "1981-10-29",
            street: "369 Walnut St",
            city: "Atlanta",
            state: "GA",
            zipCode: "30301",
        },
        {
            firstName: "Brandon",
            lastName: "Clark",
            startDate: "2022-03-15",
            department: "Engineering",
            birthDate: "1997-08-19",
            street: "741 Aspen St",
            city: "Austin",
            state: "TX",
            zipCode: "73301",
        },
        {
            firstName: "Laura",
            lastName: "Rodriguez",
            startDate: "2013-09-09",
            department: "Marketing",
            birthDate: "1979-04-11",
            street: "258 Dogwood St",
            city: "Miami",
            state: "FL",
            zipCode: "33101",
        },
        {
            firstName: "Kevin",
            lastName: "Lewis",
            startDate: "2011-05-20",
            department: "Sales",
            birthDate: "1980-12-30",
            street: "963 Hickory St",
            city: "Portland",
            state: "OR",
            zipCode: "97201",
        }
    ],
};

export const employeesSlice = createSlice({
    name: "employees",
    // `createSlice` will infer the state type from the `initialState` argument
    initialState,
    reducers: {
        addEmployee: (state, action: PayloadAction<Employee>) => {
            state.employees.push(action.payload);
        },
    },
});

export const { addEmployee } = employeesSlice.actions;

export default employeesSlice.reducer;
